IMAGE_NAME = "hashicorp/bionic64"
N = 2

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        config.vm.synced_folder '.', '/vagrant', disabled: true
    end
      
    config.vm.define "k8s-master" do |master|
        master.vm.provider "virtualbox" do |v|
            v.memory = 4096
            v.cpus = 2
        end
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network" ip: "192.168.6.150"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "../Ansible/kubernetes-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.6.150",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.provider "virtualbox" do |v|
                v.memory = 8192
                v.cpus = 4
            end
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.6.#{i + 150}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "../Ansible/kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.6.#{i + 150}",
                }
            end
        end
    end
end