master:
  jenkinsUrl: http://jenkins.192.168.6.200.nip.io/
  jenkinsAdminEmail: halilibrahimdagkilic@gmail.com
  ingress:
    enabled: true
    # Override for the default paths that map requests to the backend
    apiVersion: "networking.k8s.io/v1beta1"
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.192.168.6.200.nip.io

persistence:
  storageClass: "local-path"

